import Header from "@/component/Header";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Login",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="max-w-[1480px] mx-auto">
      <Header />
      {children}
    </main>
  );
}
