import Header from "@/component/Header";
import DashboardLayout from "@/component/admin/DashboardLayout";
import AppWrapper from "@/helpers/AppWrapper";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AppWrapper>
      <DashboardLayout>{children}</DashboardLayout>;
    </AppWrapper>
  );
}
